[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "cancun"

# Variables de entorno (.env) accesibles desde scripts y tests
# Útil para fork testing con un RPC de mainnet/L2
# fs_permissions = [{ access = "read", path = "./" }]

# Ver más opciones de configuración:
# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
